server:
  port: 8083

info:
  app:
    name: "Task Manager"
    description: "Pet project T1 open school Stream 13"
    version: "0.0.1"

spring:
  application:
    name: taskmanager

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
    driverClassName: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console



logging:
  level:
    org.springframework: INFO
    org.example.taskmanager: DEBUG


management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: task_notification
  producer:
    enable: true
  topic:
    task_notification_registration: task_notification_registration

email:
  username: kamserg1608@gmail.com
  password: password