server:
  port: 8083

info:
  app:
    name: "Task Manager"
    description: "Pet project T1 open school Stream 13"
    version: "0.0.1"

spring:
  application:
    name: taskmanager

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: "0000"
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework: INFO
    org.example.taskmanager: DEBUG

t1:
  http:
    request:
      logger:
        enabled: true
        log-level: INFO


management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: task_notification
  producer:
    enable: true
  topic:
    task_notification_registration: task_notification_registration

email:
  username: kamserg1608@gmail.com
  password: password

security:
  token:
    key: tstrsg4g34whysersh5ttrs4g34whysersh5ttrs4g34whysersh5ttrs4g34whysersh5
    expiration: 86400000